# Standard settings
edition = "2024"  # Use Rust 2024 edition formatting rules
max_width = 100   # Maximum line width before wrapping
tab_spaces = 4    # Number of spaces per indentation level
newline_style = "Unix"  # Use LF line endings instead of CRLF

# Additional settings for better code style
use_field_init_shorthand = true  # Use "field" instead of "field: field" in struct initialization when possible
use_try_shorthand = true         # Use "expr?" instead of "try!(expr)" for error propagation
format_code_in_doc_comments = true  # Apply formatting to code blocks in documentation comments
imports_granularity = "Module"   # Group imports by module rather than having one import per line
group_imports = "StdExternalCrate"  # Group imports by standard library, external crates, and local modules
